### ISSUE TITLE
When I remove `transformerRenameClass` , there are other problems, and the custom attributes in the class do not take effect.

### ISSUE THREAD

**Issue by liwenfengg** [unocss-applet/unocss-applet#3]
[1#issuecomment-1216663855 ](https://github.com/unocss-applet/unocss-applet/issues/1#issuecomment-1216663855)

When I remove `transformerRenameClass` , there are other problems, and the custom attributes in the class do not take effect.

![image](https://user-images.githubusercontent.com/40257198/185023925-57c6a52c-29aa-4b29-8298-0ec5b40d7e49.png)

This is the [demo repo](https://github.com/liwenfengg/cloudio-uni-preset-vue-vite-ts-unocss-applet), you can have a try.

**Comment by zguolee** [comment]
I notice that there are some errors in your configuration, you should set 
```ts
presetApplet({ enableApplet: !(process.env.UNI_PLATFORM === 'h5') }),
transformerRenameClass({ enableRename: !(process.env.UNI_PLATFORM === 'h5') }),
```
and delete `transformerVariantGroup()` then will work.
The `bg-[url('https://raw.githubusercontent.com/unocss/unocss/main/playground/public/icon-gray.svg')]` maybe a bug, you can try it at `https://uno.antfu.me/play/`, it does not work too, but [there](https://uno.antfu.me/?s=bg-[url(%27https://raw.githubusercontent.com/unocss/unocss/main/playground/public/icon-gray.svg%27)]) work.

**Comment by zguolee** [comment]
> [1#issuecomment-1216663855 ](https://github.com/unocss-applet/unocss-applet/issues/1#issuecomment-1216663855)
> 
> When I remove `transformerRenameClass` , there are other problems, and the custom attributes in the class do not take effect.
> 
> ![image](https://user-images.githubusercontent.com/40257198/185023925-57c6a52c-29aa-4b29-8298-0ec5b40d7e49.png)
> 
> This is the [demo repo](https://github.com/liwenfengg/cloudio-uni-preset-vue-vite-ts-unocss-applet), you can have a try.

Sorry, I wrote wrong [1#issuecomment-1216663855 ](https://github.com/unocss-applet/unocss-applet/issues/1#issuecomment-1216663855).

**Comment by liwenfengg** [comment]
> I notice that there are some errors in your configuration, you should set
> 
> ```ts
> presetApplet({ enableApplet: !(process.env.UNI_PLATFORM === 'h5') }),
> transformerRenameClass({ enableRename: !(process.env.UNI_PLATFORM === 'h5') }),
> ```
> 
> and delete `transformerVariantGroup()` then will work. The `bg-[url('https://raw.githubusercontent.com/unocss/unocss/main/playground/public/icon-gray.svg')]` maybe a bug, you can try it at `https://uno.antfu.me/play/`, it does not work too, but [there](https://uno.antfu.me/?s=bg-%5Burl(%27https://raw.githubusercontent.com/unocss/unocss/main/playground/public/icon-gray.svg%27)%5D) work.

Nice work!
Now, only this `class="bg-[url('https://raw.githubusercontent.com/unocss/unocss/main/playground/public/icon-gray.svg')]"`  doesn't take effect

But I found other problems, still about `uni-easyinput` in `uni-ui`.

![image](https://user-images.githubusercontent.com/40257198/185099483-be33e97c-bd37-47f2-ae74-0e305e0894f2.png)
![image](https://user-images.githubusercontent.com/40257198/185099620-0b3ba6ce-c7e9-439b-bfde-24109041dbd3.png)

**Comment by zguolee** [comment]
I find the solution for `class="bg-[url('https://raw.githubusercontent.com/unocss/unocss/main/playground/public/icon-gray.svg')]"` just delete all the `'`, from [[How to use background images in UNOCSS？](https://github.com/unocss/unocss/issues/1387#top)](https://github.com/unocss/unocss/issues/1387#issuecomment-1207744388) and we have also made corresponding changes(`v0.1.1`). In addition, building Android and iOS is not the goal of this repo, so we can only try to solve it, but not sure.

**Comment by zguolee** [comment]
> > I notice that there are some errors in your configuration, you should set
> > ```ts
> > presetApplet({ enableApplet: !(process.env.UNI_PLATFORM === 'h5') }),
> > transformerRenameClass({ enableRename: !(process.env.UNI_PLATFORM === 'h5') }),
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and delete `transformerVariantGroup()` then will work. The `bg-[url('https://raw.githubusercontent.com/unocss/unocss/main/playground/public/icon-gray.svg')]` maybe a bug, you can try it at `https://uno.antfu.me/play/`, it does not work too, but [there](https://uno.antfu.me/?s=bg-%5Burl(%27https://raw.githubusercontent.com/unocss/unocss/main/playground/public/icon-gray.svg%27)%5D) work.
> 
> Nice work! Now, only this `class="bg-[url('https://raw.githubusercontent.com/unocss/unocss/main/playground/public/icon-gray.svg')]"` doesn't take effect
> 
> But I found other problems, still about `uni-easyinput` in `uni-ui`.
> 
> ![image](https://user-images.githubusercontent.com/40257198/185099483-be33e97c-bd37-47f2-ae74-0e305e0894f2.png) ![image](https://user-images.githubusercontent.com/40257198/185099620-0b3ba6ce-c7e9-439b-bfde-24109041dbd3.png)
> 
> This is the [demo repo](https://github.com/liwenfengg/cloudio-uni-preset-vue-vite-ts-unocss-applet), you can have a try.

We have fixed the problem and thanked the issues provided. In addition, what is the HBuilderX version you use?

**Comment by liwenfengg** [comment]
> > > 我注意到您的配置中有一些错误，您应该设置
> > > ```ts
> > > presetApplet({ enableApplet: !(process.env.UNI_PLATFORM === 'h5') }),
> > > transformerRenameClass({ enableRename: !(process.env.UNI_PLATFORM === 'h5') }),
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 然后删除`transformerVariantGroup()`就可以了。可能是一个错误，您可以在`bg-[url('https://raw.githubusercontent.com/unocss/unocss/main/playground/public/icon-gray.svg')]`上尝试`https://uno.antfu.me/play/`，它也不起作用，但[在那里](https://uno.antfu.me/?s=bg-%5Burl(%27https://raw.githubusercontent.com/unocss/unocss/main/playground/public/icon-gray.svg%27)%5D)工作。
> > 
> > 
> > 干得好！现在，只有这个`class="bg-[url('https://raw.githubusercontent.com/unocss/unocss/main/playground/public/icon-gray.svg')]"`不生效
> > 但我发现了其他问题，仍然`uni-easyinput`在`uni-ui`.
> > ![图片](https://user-images.githubusercontent.com/40257198/185099483-be33e97c-bd37-47f2-ae74-0e305e0894f2.png) ![图片](https://user-images.githubusercontent.com/40257198/185099620-0b3ba6ce-c7e9-439b-bfde-24109041dbd3.png)
> > 这是[demo repo](https://github.com/liwenfengg/cloudio-uni-preset-vue-vite-ts-unocss-applet)，你可以试试。
> 
> 我们已解决问题并感谢提供的问题。另外，你用的HBuilderX版本是什么？

thanks

The version of HBuilderX I'm using is `3.5.3.20220729`

![image](https://user-images.githubusercontent.com/40257198/185281299-048ae540-b870-4571-a9a6-3b028bee2ca9.png)

when I removed the `'` in `class="bg-[url('https://raw.githubusercontent.com/unocss/unocss/main/playground/public/icon-gray.svg')]"`  , It works on the h5 side, but it doesn't work on the app side, either with quotation marks or without quotation marks.

![image](https://user-images.githubusercontent.com/40257198/185281266-9a7cc220-5e6e-45e1-878a-84bcea7a5584.png)

**Comment by zguolee** [comment]
Maybe you should turn on the VPN in Android/iOS or change a domestic [picture](https://www.baidu.com/img/PCtm_d9c8750bed0b3c7d089fa7d55720d6cf.png). Static files 
and `@unocss/preset-attributify` may not be as supported as applets. `attributify` may do it later, but we are not sure.

**Comment by liwenfengg** [comment]
> Maybe you should turn on the VPN in Android/iOS or change a domestic [picture](https://www.baidu.com/img/PCtm_d9c8750bed0b3c7d089fa7d55720d6cf.png). Static files and `@unocss/preset-attributify` may not be as supported as applets. `attributify` may do it later, but we are not sure.

It takes effect without adding/.    
his is really strange.....

![image](https://user-images.githubusercontent.com/40257198/185307904-b72e9207-8791-4ed4-b45b-0aef645e0b1a.png)

**Comment by liwenfengg** [comment]
in app side, `shortcuts` and `Attributify Mode` Still not supported

`text="base #F2FF"`

[attributify-mode](https://github.com/unocss/unocss/tree/main/packages/preset-attributify/#attributify-mode)

![image](https://user-images.githubusercontent.com/40257198/185310325-614d1af2-f686-4470-ac66-861f8971acbd.png)

**Comment by zguolee** [comment]
`attributify` is not sure if it can be achieved in the end, we will try it later, but not now, you can open a new issue.
